# Dockerfile.waitress
FROM python:3.12-slim-bullseye

WORKDIR /app

RUN pip install waitress --upgrade requests

# Copy the waitress_proxy.py script into the container
COPY waitress_proxy.py /app/waitress_proxy.py

# Entrypoint to run the proxy script
ENTRYPOINT ["python", "waitress_proxy.py"]
